// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbk6hvJQsAXXkvyYsmfn0SS3CsWSzoeFs',
    appId: '1:481932526170:web:c1d83d357f40a4d1068e63',
    messagingSenderId: '481932526170',
    projectId: 'campusfit-b30e7',
    authDomain: 'campusfit-b30e7.firebaseapp.com',
    storageBucket: 'campusfit-b30e7.firebasestorage.app',
    measurementId: 'G-ZT2FPNF9MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf8RQDgzB9XBcl1aflUggYTx8DcSpBClc',
    appId: '1:481932526170:android:1f324fbae3556252068e63',
    messagingSenderId: '481932526170',
    projectId: 'campusfit-b30e7',
    storageBucket: 'campusfit-b30e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pRBVtXB1Axh03IYeHsoWdUWrpzQHmec',
    appId: '1:481932526170:ios:ec409c9587b99939068e63',
    messagingSenderId: '481932526170',
    projectId: 'campusfit-b30e7',
    storageBucket: 'campusfit-b30e7.firebasestorage.app',
    iosBundleId: 'com.example.campusfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0pRBVtXB1Axh03IYeHsoWdUWrpzQHmec',
    appId: '1:481932526170:ios:ec409c9587b99939068e63',
    messagingSenderId: '481932526170',
    projectId: 'campusfit-b30e7',
    storageBucket: 'campusfit-b30e7.firebasestorage.app',
    iosBundleId: 'com.example.campusfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbk6hvJQsAXXkvyYsmfn0SS3CsWSzoeFs',
    appId: '1:481932526170:web:05995764e40a14b9068e63',
    messagingSenderId: '481932526170',
    projectId: 'campusfit-b30e7',
    authDomain: 'campusfit-b30e7.firebaseapp.com',
    storageBucket: 'campusfit-b30e7.firebasestorage.app',
    measurementId: 'G-PNJ6Y5BX81',
  );
}
